<a href="https://colab.research.google.com/github/sugban/Python-Learning-/blob/main/Lesson%2022/Lesson_22_Work_with_excel_File_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Excel file - read, create, update 

* xlrd module is used to extract data from a spreadsheet
<pre>
import xlrd
</pre>

In [1]:
# importing module

import xlrd

In [5]:
# Loading Excel file

exl_file = xlrd.open_workbook('Newcustomer.xlsx')

*There could be multiple workbooks(sheets) inside a single excel file. So to work on sheet by sheet or one sheet, we will use **'sheet_by_index()'** function and pass the index number of the sheet we want to work on*

In [6]:
# Storing the first sheet into a variable

purchase = exl_file.sheet_by_index(0)

In [7]:
# Printing various cell values

print("Value of 0-0 cell: ",purchase.cell_value(0, 0)) # printing value from first row and first column

print("Value of 20-1 cell: ",purchase.cell_value(20, 0))  # printing value from 20th row and first column

Value of 0-0 cell:  first_name
Value of 20-1 cell:  Gaston

In [8]:
# Get the no of rows and columns

print("Number of Rows: ", purchase.nrows)
print("Number of Columns: ",purchase.ncols)

Number of Rows:  716
Number of Columns:  10

In [9]:
# Get all column names

print("Columns in the worksheet are: ")

for col in range(purchase.ncols):
    print(purchase.cell_value(0,col))

Columns in the worksheet are:
first_name
last_name
gender
past_3_years_bike_related_purchases
deceased_indicator
owns_car
tenure
property_valuation
Rank
Value

In [10]:
# to get data from a particular column - the first column

purchase.cell_value(0, 0)
 
for row in range(purchase.nrows):
    print(purchase.cell_value(row, 0))

first_name
Chickie
Morly
Ardelis
Lucine
Melinda
Druci
Rutledge
Nancie
Duff
Barthel
Rockwell
Wheeler
Melba
Mandie
Marcelia
Winnifred
Odilia
Karly
Teddie
Gaston
Brena
Dyane
Claudine
Blinnie
Brien
Sybilla
Maisie
Arleen
Colene
Gipsy
Sheena
Gale
Thaxter
Taylor
Griswold
Lavena
Martelle
Briant
Lorrie
Jedediah
Kaine
Loise
Cristen
Dorothy
Rosmunda
Rozamond
Gunner
Sherilyn
Bessie
Kevina
Hasheem
Tobias
Glennis
Chanda
Katheryn
Sumner
Valerie
Gardie
Sean
Marysa
Ossie
Sid
Patricia
Symon
Karlik
Bengt
Evangelin
Hanny
Gina
Reynold
Flossy
Cristen
Griffith
Jamie
Lyon
Franciska
Jordan
Meriel
Dolley
Rollo
Jerrine
Roddy
Viki
Ashby
Peria
Rebeca
Ricki
Georgetta
Bambi
Aurie
Lacy
Malorie
Shepperd
Daryl
Norina
My
Isak
Grannie
Welby
Glenn
Nadiya
Tyne
Christie
Agnella
Daisy
Denys
Archibald
Feodor
Skippie
Tessa
Roseanne
Nichole
Amil
Shawna
Robert
Elvira
Juliana
Regine
Abner
Sawyer
Feodor
Paten
Loria
Tanya
Omero
Iain
Keriann
Conroy
Dorian
Harlin
Eustacia
Maury
Reggie
Kinna
Maurizio
Elbertina
Franklin
Allyson
Ermentrude
Alanna
Vincent
Charlena
Rosemonde
Benoit
Jenelle
Tannie
Mick
Tabbie
Shane
Roberta
Kippy
Cami
Dorian
Giorgi
Kort
Tobiah
Hersh
Wyn
Maribeth
Abigale
Gothart
Danny
Deborah
Latrena
Leticia
Farra
Robenia
Roman
Solomon
Katharine
Cammy
Ellsworth
Federico
Ferdy
Sunny
Shadow
Sharai
Celeste
Lea
Dyann
Delly
Kaela
Evonne
Shannen
Bogey
Zondra
Barnebas
Gerri
Antonietta
Raff
Lark
Cletis
Theresa
Philbert
Egon
Timi
Dominick
Raye
Becka
Verla
Sherrie
Konstanze
Bink
Taber
Giana
Morton
Paquito
Shelli
Kermit
Biddie
Geoff
Tiphanie
Zollie
Daisy
Emelen
Manya
Brynna
Loleta
Claudine
Seamus
Guss
Roch
Audry
Clari
Zach
Parnell
Honey
Sonny
Deirdre
Zechariah
Carry
Nil
Erhard
Vitia
Haskell
Ebony
Nicole
Celestina
Tannie
Bessy
Diego
Cissiee
Eddy
Caron
Sandor
Delinda
Hussein
Kaylyn
Brynn
Pace
Muffin
Allsun
Kenneth
Clotilda
Daisi
Gerik
Arty
Whit
Rowan
Ian
Harriet
Sada
Jenelle
Gabrila
Almira
Arty
Alexa
Palmer
Porter
Giffie
Tamar
Kipp
Packston
Demetria
Lura
Estevan
Aloysius
Bastien
Otha
Dwayne
Leese
Kippar
Corinna
Laurie
Tanner
Hilliard
Justinn
Art
Dennis
Freddi
Salomon
Etan
Donaugh
Harwell
Cheston
Suzy
Guenna
Opal
Kipper
Marilin
Arel
Kit
Skipp
Frederich
Rodolph
Craggie
Giralda
Rodney
Gleda
Melany
Claudell
Garwin
Bunny
Matias
Anet
Katie
Celia
Stearne
Tristam
Heloise
Marcellina
Lucky
Erasmus
Carita
Lynnett
Thorn
Norah
Moina
Ceciley
Torry
Sigismund
Irvine
Tomkin
Genni
Carola
Fitzgerald
Ingmar
Tina
Adolpho
Kelsey
Alexina
Dawn
Claudette
Anthony
Liane
Renell
Cliff
George
Katleen
Inglebert
Jammal
Adriane
Emelia
Sofie
Elmira
Worthington
Bailey
Perry
Antony
Nico
Ivy
Hilario
Jim
Jacobo
Gretel
Jethro
Dwain
Lucretia
Claude
Donn
Laurel
Elvira
Angie
Terrence
Katy
Sammy
Morganica
Nils
Beverlee
Cami
Reiko
Cord
Gabey
Jacqui
Byrom
Worthington
Chico
Davidde
Charlie
Barth
Padriac
Olive
Benedict
Virginia
Oswald
Ailyn
Karol
Esdras
Wilfrid
Charmain
Bobby
Shepherd
Berenice
Cordi
Debbie
Flin
Noel
Letizia
Kiley
Ethelred
Dena
Wyndham
Rochette
Jamal
Levin
Marinna
Gilbert
Chaim
Anson
Caitrin
Rozamond
Maximilian
Ajay
Jamison
Dorian
Nicol
Nev
Lucius
Francisca
Farlie
Beverlee
Lek
Ewell
Madison
Ardis
Wheeler
Terrel
Lissa
Leisha
Kearney
Shellysheldon
Reinhard
Menard
Andree
Pierrette
Demott
Wendye
Irvin
Austine
Wolf
Aldin
Sindee
Truman
Leticia
Caritta
Annabelle
Darryl
Orly
Nicol
Nobe
Stephen
Giselbert
Lisette
Xenia
Essie
Lillis
Ted
Nixie
Briana
Wrennie
Sibylla
Kariotta
Wylie
Lizbeth
Averil
Myrtie
Ross
Sibby
Selle
Andrew
Maurizia
Keenan
Davide
Renie
Debby
Harvey
Patrice
Arman
Gardiner
Jillane
Lynnell
Mandie
Ferdinand
Emeline
Cissiee
Roldan
Barth
Alta
Marc
Bertine
Wilbert
Miran
Dorotea
Jenny
Beatrix
Nalani
Inglebert
Brendis
Glendon
Morganica
Son
Bartram
Halette
Killie
Mandi
Yardley
Shepperd
Fancie
Micheil
Cecily
Sinclair
Tomaso
Gilli
Errick
Damian
Agnola
Riki
Mikol
Phyllis
Burt
Frederigo
Cal
Stephani
Meade
Leighton
Petr
Yorgos
Simmonds
Cazzie
Geoff
Deirdre
Juliann
Janaye
Dylan
Mel
Elvin
Sonni
Kellina
Therese
Pansie
Reinaldos
Calhoun
Winn
Rafi
Verne
Eleonora
Fayre
Eachelle
Carl
Cordie
Jackie
Carroll
Frans
Amara
Anthony
Cherye
Ansell
Rosene
Darlleen
Bryon
Luci
Sloan
Otes
Davie
Meade
Rikki
Adria
Rowen
Boothe
Noak
Callean
Keelby
Rodrique
Manny
Becky
Tessa
Renate
Toma
Dorie
Ellie
Teodor
Jared
Andy
Catha
Melosa
Maris
Wilburt
Guilbert
Meridith
Gerta
Karrah
Alick
Casandra
Maurine
Darwin
Hayes
Piper
Markus
Sile
Craggy
Egor
Reinald
Kissie
Quentin
Karoly
Clarine
Clemmie
Randall
Donica
Lotty
Marie-jeanne
Rodolphe
Thorvald
Paulina
Ricki
Lizette
Jeno
Raleigh
Zachariah
Lesley
Adriena
Shay
Karney
Latrena
Kelcie
Fabio
Heall
Rickert
Hedwig
Andriana
Nilson
Denny
Olia
Shaw
Brook
Dolorita
Harman
Ilise
Julita
Ashlen
Keely
Poul
Rubia
Francklin
Lezlie
Kathe
Dulce
Felice
Joane
Ogdan
Kizzee
Stephi
Martino
Morgen
Eugenie
Reinold
Jo
Jacklin
Colas
Claudetta
Cicily
Harland
Sim
Shanon
Chryste
Edin
Nolly
Michele
Philbert
Maximilien
Benedikta
Afton
Sonia
Benedikt
Don
Moll
Jammie
Inglis
Clarabelle
Tillie
Irving
Evered
Mavra
Alex
Aundrea
Esme
Beverly
Artemis
Daryle
Leona
Bertrando
Lauralee
Consalve
Lolly
Vyky
Jermaine
Bryan
Renie
Weidar
Datha
Ferdinand
Burk
Melloney
Dickie
Sylas

In [11]:
# Get first 10 rows for 3 columns

for row in range(11): # looping 10 times to get the data from first 10 rows
    for col in range(3): # looping 3 times to get the data in first 3 columns

        print(purchase.cell_value(row,col), end="\t ")
    print()

first_name	 last_name	 gender
Chickie	 Brister	 Male
Morly	 Genery	 Male
Ardelis	 Forrester	 Female
Lucine	 Stutt	 Female
Melinda	 Hadlee	 Female
Druci	 Brandli	 Female
Rutledge	 Hallt	 Male
Nancie	 Vian	 Female
Duff	 Karlowicz	 Male
Barthel	 Docket	 Male

In [12]:
# to extract a particular row value - second row (without header first row)
 
print(purchase.row_values(1))

['Chickie', 'Brister', 'Male', 86.0, 'N', 'Yes', 14.0, 6.0, 1.0, 1.71875]

### Writing to an excel sheet

* to write and modify data in an excel sheet, we have to import a module xlwt
<pre>
import xlwt
</pre>

In [15]:
# importing module

import xlwt
from xlwt import Workbook

In [16]:
# creating a new workbook

wb = Workbook()

In [17]:
# to create sheet, we'll use add_sheet() method

sheet1 = wb.add_sheet('Sheet 1')

In [18]:
# adding rows and columns in sheet 1

sheet1.write(0, 0, 'Student name')
sheet1.write(0, 1, 'DOB')
sheet1.write(0, 2, 'Course')
sheet1.write(0, 3, 'Year')
sheet1.write(1, 0, 'Allan')
sheet1.write(1, 1, '20-01-1999')
sheet1.write(1, 2, 'Data Science')
sheet1.write(1, 3, '2020')
sheet1.write(2, 0, 'RAJ')
sheet1.write(2, 1, '12-05-1996')
sheet1.write(2, 2, 'UX')
sheet1.write(2, 3, '2018')

# giving workbook a name and saving it 

wb.save('Student.xlsx')

In [19]:
# to open to read

exl_file = xlrd.open_workbook('Student.xlsx')

student = exl_file.sheet_by_index(0)

In [20]:
print(student.nrows)
print(student.ncols)

3
4

In [21]:
# to read the file all content

for row in range(student.nrows):
  print(student.row_values(row))

['Student name', 'DOB', 'Course', 'Year']
['Allan', '20-01-1999', 'Data Science', '2020']
['RAJ', '12-05-1996', 'UX', '2018']